name: Pull request labeler

# FIXME: Consider adding the `issue_comment` event to change labels based on generic, non-review pull request comments.
#        Consider the trade off of how spammy it can be (one CI run per comment) and how useful it would be to have.
#        Consider alternatives to `issue_comment`.
on: [push]

jobs:
  label_pull_request:
    runs-on: ubuntu-22.04
    if: always() && github.repository == 'SerenityOS/serenity'

    steps:
      - uses: actions/checkout@v4

      - name: Label pull request
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./Meta/label-pull-requests.js')
            script({github, context})
